name: Trigger auto deployment for album-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/**'
    - '.github/workflows/album-api-AutoDeployTrigger-32623e4d-9aef-4a1a-ba42-085cb1306748.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ALBUMAPI_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/src 
          registryUrl: caeb05a0bb46acr.azurecr.io
          registryUsername: ${{ secrets.ALBUMAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ALBUMAPI_REGISTRY_PASSWORD }}
          containerAppName: album-api
          resourceGroup: container-rg
          imageToBuild: caeb05a0bb46acr.azurecr.io/album-api:${{ github.sha }}
          dockerfilePath: Dockerfile

     

